### ISSUE TITLE
Unauthenticated packages in Debian Stretch

### ISSUE THREAD

**Issue by mcastillof** [michaelfranzl/rpi23-gen-image#11]
I'm having the following message at the end of the build: 

>  WARNING: The following packages cannot be authenticated!
  libc6 libc-bin multiarch-support libgnutls30 libexpat1
E: There were unauthenticated packages and -y was used without --allow-unauthenticated

Build log attached.

[buildLog.txt](https://github.com/michaelfranzl/rpi23-gen-image/files/1117566/buildLog.txt)

**Comment by michaelfranzl** [comment]
This seems to be a temporary problem with the official Debian package repositories, and not with the script. Maybe retry a bit later...

**Comment by jodal** [comment]
I got the same error building on top of Ubuntu 17.04. It seems to be a permissions issue caused by APT dropping permissions and changing to the `_apt` user.

A workaround is:

``` diff
diff --git a/bootstrap.d/11-apt.sh b/bootstrap.d/11-apt.sh
index 0d24564..ba06200 100644
--- a/bootstrap.d/11-apt.sh
+++ b/bootstrap.d/11-apt.sh
@@ -11,6 +11,7 @@ if [ -z "$APT_PROXY" ] ; then
   sed -i "s/\"\"/\"${APT_PROXY}\"/" "${ETC_DIR}/apt/apt.conf.d/10proxy"
 fi

+install_readonly files/apt/99aptsandbox "${ETC_DIR}/apt/apt.conf.d/99aptsandbox"

 install_readonly files/apt/sources.list "${ETC_DIR}/apt/sources.list"

diff --git a/files/apt/99aptsandbox b/files/apt/99aptsandbox
new file mode 100644
index 0000000..2c0f659
--- /dev/null
+++ b/files/apt/99aptsandbox
@@ -0,0 +1 @@
+APT::Sandbox::User "root";
```

**Comment by coquizen** [comment]
For the record, this patch also works with Debian Stretch

**Comment by h01ger** [comment]
I can confirm this is needed for Stretch 9.2 as well.

**Comment by michaelfranzl** [comment]
Shortly after I published this script, Debian Stretch changed `apt-get` to run as a sandboxed (non-root) user. The actual problem was that that `qemu` was installed executable only for the root user. Changing the permissions for `qemu` fixes the error message `"There were unauthenticated packages and -y was used without --allow-unauthenticated"`.

The solution by @jodal fixes this issue too, but `apt-get` should really be run as unprivileged user for security reasons.
