### ISSUE TITLE
ENABLE_DHCP=true and ENABLE_IFNAMES=true not working together

### ISSUE THREAD

**Issue by D-Albers** [michaelfranzl/rpi23-gen-image#8]
The combination of _ENABLE_DHCP=true_ and _ENABLE_IFNAMES=true_ are not working together, because the network ha not the expected name _eth0_.

**Comment by michaelfranzl** [comment]
Removed ENABLE_IFNAMES feature because it relied on kernel log messages specific to the Raspberry flavored kernel. It never worked with the mainline Linux kernel because its boot messages are different. If you need to customize network device names, you should do that manually after booting into the RPi.
